# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    tags:
      - '*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
  
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Windows build
      run: dotnet publish --no-restore -r win-x64
    - name: Linux build
      run: dotnet publish --no-restore -r linux-x64
    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          bin/Release/win-x64/publish/RimWorldModUpdater-win-x64.exe
          bin/Release/linux-x64/publish/RimWorldModUpdater-linux-x64
